on:
  pull_request:
  push:
    branches: [runner]

jobs:
  home:
    name: Build home standalone
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - name: Build Configuration
        run: nix build --impure .#homeConfigurations.home.activationPackage
      - name: Apply Configuration
        run: ./result/activate
  darwin:
    name: Build darwin configuration
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - name: Fix conflicted nix conf
        run: mv /etc/nix/nix.conf /etc/nix/nix.conf.before-nix-darwin
      - name: Build Configuration
        run: nix build --impure .#darwinConfigurations.darwin.system
      - name: Apply Configuration
        run: ./result/sw/bin/darwin-rebuild switch --impure --flake .#darwin
